fix: Remove unused dockerfile dependency
No longer needed after https://github.com/frappe/agent/commit/4369ebe3a3cec90d0330694fb62e3ea9cfad581d

pip install dockerfile fails on ARM with

```python
    Running setup.py install for dockerfile: started
    Running setup.py install for dockerfile: finished with status 'error'

:stderr:   ERROR: Command errored out with exit status 1:
   command: /home/frappe/agent/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5lvzkoe0/dockerfile/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5lvzkoe0/dockerfile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-009hdutr
       cwd: /tmp/pip-install-5lvzkoe0/dockerfile/
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  $ GOPATH=/tmp/tmpcdjeh4hk go get -d
  error: [Errno 2] No such file or directory: 'go'
  ----------------------------------------
  ERROR: Failed building wheel for dockerfile
    ERROR: Command errored out with exit status 1:
     command: /home/frappe/agent/env/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5lvzkoe0/dockerfile/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5lvzkoe0/dockerfile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pgxk6co2/install-record.txt --single-version-externally-managed --compile --install-headers /home/frappe/agent/env/include/site/python3.8/dockerfile
         cwd: /tmp/pip-install-5lvzkoe0/dockerfile/
    Complete output (5 lines):
    running install
    running build
    running build_ext
    $ GOPATH=/tmp/tmpvmtm3abz go get -d
    error: [Errno 2] No such file or directory: 'go'
    ----------------------------------------
```